apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test7233 
  janus-idp.io/tekton: test7233
  backstage.io/kubernetes-id: test7233
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: test7233
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  