apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: test7233-gitops
  description: This is GitOps manifest for test7233   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: test7233
    janus-idp.io/tekton: test7233 
    backstage.io/kubernetes-id: test7233 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:test7233
